---
- name: Onboarding routers
  hosts: routers
  ansible_get_facts: false
  task:
    - name : configure banner
      ios_banner:
        banner: motd
        text: '{{ lookup ("file","banner.cfg")}}'