---
- name: IOS config
  hosts: routes
  gather_facts: false

  tasks:
    # - name: congig
    #   ios_config:
    #     lines:
    #       - do sh run
    - name: config int
      ios_config:
        parents: interface GigabitEthernet0/3
        lines:
          - ip address 23.22.22.22 255.255.255.0
        diff_against: startup
        save_when: modified
    - name: save multiple
      ios_config:
        parents: "{{item}}"
        lines:
          - description backup_int
        after:
          - no shutdown
        save_when: modified
      with_items:
        - interface GigabitEthernet0/0
        - interface GigabitEthernet0/3