---
- name: My first ansible program
  hosts: device_group
  tasks:
    - name: Execute show commands
      ios_command:
        command:
          - show run
          - sh ip int bri
        register: show_output
      debug:
        var: show_output