---
- name: My first ansible program
  hosts: device_group
  tasks:
    - name: Execute show commands
      cisco.ios.ios_command:
        commands:
          - show run
          - sh ip int bri
      register: show_output
    - debug:
        var: show_output
